os:
  - linux
  - osx
language: rust
rust:
  - stable
  - nightly
cache: cargo
matrix:
  allow_features:
    - rust: nightly
  fast_finish: true
stages:
  - test
  - name: build
    if: branch = master
jobs:
  include:
    - stage: test
      script: cargo test
    - stage: build
      script: cargo build --release --verbose
      deploy:
        provider: releases
        api_key: $GITHUB_PAT
        file: $TRAVIS_FILENAME
        on:
          tags: true
        skip_cleanup: true
      before_deploy:
        - export TRAVIS_FILENAME="logik-${TRAVIS_OS_NAME}-${TRAVIS_TAG}-$(git log --format=%h -1).tar.gz"
        - tar -czvf $TRAVIS_FILENAME target/release
