os:
    - linux
    - osx
language: rust
rust:
    - stable
    - nightly
cache: cargo
matrix:
    allow_features:
        - rust: nightly
    fast_finish: true
script:
    - cargo build --release --verbose
before_deploy:
    - git config --local user.name "Travis CI",
    - git config --local user.email "noreply@users.rs-logik.github.com"
    - export TRAVIS_TAG="nightly"
    - git tag $TRAVIS_TAG
deploy:
    provider: releases
    api_key: $GITHUB_PAT
    file: target/release/repl
    skip_cleanup: true

